[general]
import = [
    "~/.config/alacritty/themes/themes/pastel_dark.toml"
]

[terminal.shell]
program = "/usr/bin/zsh"

[window]
dimensions = { columns = 100, lines = 30 }
position = { x = 2250, y = 1180 }

[font]
size = 10

# Дополнительные настройки
[env]
TERM = "xterm-256color"

[terminal]
